version: '3'

services:
  tapo-P110-exporter:
    image: cardif99/p110-exporter:latest
    container_name: p110-exporter
    volumes:
       - ./tapo.yaml:/app/tapo.yaml:ro
    ports:
      - 9333:9333
    environment:
      - TAPO_EMAIL=YOUR@EMAIL.COM
      - TAPO_PASSWORD=CHANGE_ME
      - PORT=9333 # optional
